[tool.pyright]
exclude = ["alembic"]
pythonVersion = "3.12"
typeCheckingMode = "basic"
reportUnusedImport = "error"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingParameterType = "error"
reportUnusedVariable = "warning"

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = ["alembic"]

[tool.ruff.format]
preview = true
quote-style = "single"
skip-magic-trailing-comma = false

[tool.ruff.lint]
preview = true
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "ARG001", # unused arguments in functions
]

ignore = [
  "E501",  # line too long, handled by black
]

[tool.ruff.lint.isort]
combine-as-imports = true